# Generated by Django 4.1.5 on 2023-01-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_school_alter_user_email_alter_user_name_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='enroll.school'),
        ),
    ]
